project_id = "npvkyiujvxyrrqdyrhas"

[functions.send-order-confirmation]
verify_jwt = true

[functions.checkout-create]
verify_jwt = true

[functions.admin-mark-paid]
verify_jwt = true

[functions.cart-price]
verify_jwt = true

[functions.chatbot]
verify_jwt = false

[functions.meshy]
verify_jwt = false